name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: PunithMohan/helloworld-custom-action@main
      with:
        commit-count: '5'
        LabelName: 'LargePRs'
        Comments: 'The PR should have less than 10 commits'
            
