name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: PunithMohan/helloworld-custom-action@v1.1
      with:
        commit-count: '5'
            
