name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
     - main
     - PR_test

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  PR_Number: ${{ github.event.pull_request.number }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: PunithMohan/helloworld-custom-action@main
      with:
        commit-count: '5'
        LabelName: 'LargePRs'
        Comments: 'The PR should have less than 10 commits'
        token: '${{ secrets.GITHUB_TOKEN }}'
        PR_Number: "${{ env.PR_Number }}"
    
      
            
